// <auto-generated />
using ApiTransporte.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ApiTransporte.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260613182402_CambiarFechaReporteAString")]
    partial class CambiarFechaReporteAString
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ApiTransporte.Models.Reporte", b =>
                {
                    b.Property<int>("IdReporte")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdReporte"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("FechaGeneracion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IdVehiculo")
                        .HasColumnType("integer");

                    b.Property<string>("LugarCompra")
                        .HasColumnType("text");

                    b.Property<string>("NombreRepuesto")
                        .HasColumnType("text");

                    b.Property<string>("TipoReporte")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("ValorRepuesto")
                        .HasColumnType("numeric");

                    b.HasKey("IdReporte");

                    b.HasIndex("IdVehiculo");

                    b.ToTable("Reporte");
                });

            modelBuilder.Entity("ApiTransporte.Models.Vehiculo", b =>
                {
                    b.Property<int>("IdVehiculo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdVehiculo"));

                    b.Property<int>("Anio")
                        .HasColumnType("integer");

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean");

                    b.Property<string>("EstadoDpf")
                        .HasColumnType("text");

                    b.Property<string>("EstadoExtintor")
                        .HasColumnType("text");

                    b.Property<string>("EstadoRevision")
                        .HasColumnType("text");

                    b.Property<string>("FechaProximaMantencion")
                        .HasColumnType("text");

                    b.Property<string>("FechaRevisionTecnica")
                        .HasColumnType("text");

                    b.Property<string>("FechaUltimaMantencion")
                        .HasColumnType("text");

                    b.Property<int?>("IdConductor")
                        .HasColumnType("integer");

                    b.Property<string>("Marca")
                        .HasColumnType("text");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Observacion")
                        .HasColumnType("text");

                    b.Property<string>("Patente")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ProximoKilometraje")
                        .HasColumnType("integer");

                    b.HasKey("IdVehiculo");

                    b.ToTable("Vehiculo");
                });

            modelBuilder.Entity("ApiTransporte.Models.Reporte", b =>
                {
                    b.HasOne("ApiTransporte.Models.Vehiculo", "Vehiculo")
                        .WithMany("Reportes")
                        .HasForeignKey("IdVehiculo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("ApiTransporte.Models.Vehiculo", b =>
                {
                    b.Navigation("Reportes");
                });
#pragma warning restore 612, 618
        }
    }
}
